### ISSUE TITLE
Not possible to view documentation

### ISSUE THREAD

**Issue by Eddcapone** [meanbee/magento-shipping-rules#10]
I get "my-email@foo.com" has no access to Confluence at meanbee.atlassian.net.

**Comment by bobbyshaw** [comment]
This URL Is no longer publicly available, I've added an export to the repo https://github.com/meanbee/magento-shipping-rules/blob/develop/EXT-ShippingRules-140819-1522.pdf

**Comment by Eddcapone** [comment]
Shouldn't you add this link to the start page of this repo?

**Comment by bobbyshaw** [comment]
Resolved by #12. Thanks @Eddcapone.
